### ISSUE TITLE
TSMP-PDAF: Unused local variables in initialize_tsmp

### ISSUE THREAD

**Issue by jjokella** [HPSCTerrSys/TSMP#114]
In `initialize_tsmp`, the following local variables seem to be unused:
- `subsize`
- `coupkey`
- `interpfcol` / `interpfkey`
- `tcycle`
- `*pfrank`
- `i`, `j`

**Comment by kvrigor** [comment]
Yep they are. Source file for context:

https://github.com/HPSCTerrSys/TSMP/blob/833df75abf990ac3e4effd5e28975e0de7330a5b/bldsva/intf_DA/pdaf1_1/model/wrapper_tsmp.c#L32-L146

Could you raise a PR fix for this?

**Comment by jjokella** [comment]
Thanks @kvrigor - will do a PR later.
