### ISSUE TITLE
Automatic loading of ParFlow3.7 by flag

### ISSUE THREAD

**Issue by jjokella** [HPSCTerrSys/TSMP#124]
Currently ParFlow3.7 is cloned to the current `master` automatically (from  https://github.com/parflow/parflow.git).

This contradicts the way component models have generally been handled by `TSMP` up to now: The version of a component model that the user supplies is checked by the code and used exactly as supplied (after possible changes, the so-called `patches`).

As a backward-compatible alternative to the current situation, a flag could be introduced for automatic loading of the newest ParFlow. However, my suggestion would be to remove the automatic loading completely.

Code (Example for machine `JURECA`, corresponding snippets can be found for `JUWELS`, `JUSUF` and `DEEP`:
https://github.com/HPSCTerrSys/TSMP/blob/cdaf23cc31a5e892b1314239accb09d1f712b843/bldsva/intf_oas3/parflow3_7/arch/JURECA/build_interface_parflow3_7_JURECA.ksh#L39-L57

**Comment by kvrigor** [comment]
I think what you did on #125 is sufficient; no need to introduce a new flag to bring back the automatic-download behavior. The important thing is there is a way to build the desired ParFlow version (via the traditional approach of cloning the repo) and that the build succeeds.
