### ISSUE TITLE
TSMP: Update `loadenvs` scripts to Stages/2022 on JURECA/JUWELS

### ISSUE THREAD

**Issue by jjokella** [HPSCTerrSys/TSMP#134]
JURECA and JUWELS environments have been updated to `Stages/2022` recently.

Therefore, the `loadenvs` scripts for JUWELS and JURECA should be updated as well.

The default scripts will be updated, the scripts for `Stages/2020` will be renamed.

**Comment by jjokella** [comment]
- Updated `loadenvs` files in branch `master-134`. Still need to be tested.
- module `Szip` could not be loaded in `Stages/2022` (as of now). Used in ICON build.

**Comment by DCaviedesV** [comment]
Related to #156

**Comment by jjokella** [comment]
The original intent of this issue is achieved by #156
