### ISSUE TITLE
Avoid duplicity in the build system

### ISSUE THREAD

**Issue by DCaviedesV** [HPSCTerrSys/TSMP#144]
With the introduction of 4370314f986bbaf94cc44d02e466d962ff0ce5df some further duplicity of [environment scripts](https://github.com/HPSCTerrSys/TSMP/blob/4370314f986bbaf94cc44d02e466d962ff0ce5df/bldsva/machines/JUWELS/loadenvs.Intel.scalasca ) and of [CLM-compiler related code](https://github.com/HPSCTerrSys/TSMP/blob/4370314f986bbaf94cc44d02e466d962ff0ce5df/bldsva/intf_oas3/clm3_5/arch/JURECA/src.Intel.scalasca/m_FileResolv.F90).
The build system should be slimmed down to avoid these type of duplicate scripts, and have some nesting strategy that allows duplicating code across different machines and choices of compilers.

**Comment by DCaviedesV** [comment]
There are currently several important points to address with this:
1. clean up of old environment files
2. clean up of decommissioned machines
3. verify and update `GENERIC_X86`, and possibly other machines

**Comment by kgoergen** [comment]
AGROCLUSTER needs to be discussed. New_AGROCLUSTER might be relevant. I would reduce to the most relevant machines only and x86_64.

**Comment by DCaviedesV** [comment]
Part of this cleanup relates to making the current build system a bit leaner and cleaner (also related to #147), but without overdoing it in what relates to the upcoming [eTSMP build system](https://github.com/HPSCTerrSys/eTSMP).

**Comment by niklaswr** [comment]
Just a comment on 'verify and update `AGROCLUSTER`'.
If I remember correct Maxime spend much time on this and failed (on AGROCLUSTER3113). So Im not sure how quick this is reachable.

**Comment by kgoergen** [comment]
I would not go for AGROCLUSTER old or new at this point.

**Comment by DCaviedesV** [comment]
Tempted to ask why... but most importantly, let's then avoid the support for AGROCLUSTER for now @chartick

**Comment by chartick** [comment]
To update this: 

Old environment files and machines are cleaned up. 

The lib_install.sh of GENERIC_X86 script is updated to new paths and versions, but I failed to compile all the programs in there. Several needed programs also exist in software repositories of different Linux distros, but I did not manage to correctly use them in the compilation of TSMP.

JUSUF does not work out of the box, but I think that's not a high priority.

To my knowledge, CCA2 is also decommissioned.


> There are currently several important points to address with this:
> 
>     * [ ]  clean up of old environment files
> 
>     * [ ]  clean up of decommissioned machines
> 
>     * [ ]  verify and update `GENERIC_X86`
> 
>     * [ ]  verify and update `AGROCLUSTER`
> 
>     * [ ]  verify and update `JUSUF`
> 
>     * [ ]  verify and update `CCA2`

**Comment by DCaviedesV** [comment]
@chartick please provide an update on this (or close if all points are met) with the [release 1.4.0](https://github.com/HPSCTerrSys/TSMP/releases/tag/v1.4.0)

**Comment by chartick** [comment]
I am closing it. One point not fully fulfilled is the usage of GENERIC_X86. The install script has been updated in the release, but the installation is error-prone on the machines I have tested. If further work should be done on this, it should be a separate issue. All other points have been resolved in the release.
