### ISSUE TITLE
WT variable in TSMP output has a constant value of 4800 everywhere

### ISSUE THREAD

**Issue by JulianGiles** [HPSCTerrSys/TSMP#151]
The WT variable in TSMP output has a constant value of 4800 everywhere.

I am talking about the rcsm_TSMP-ERA5-eval_IBG3 run available in the JSC systems.

**Comment by niklaswr** [comment]
I checked the TSMP model output for different model-combinations:  
`WT` is constant if ParFlow is involved in coupling only. If ParFlow is not involved `WT` does vary, wherefore this seems to be some 'aimed' coupling behavior.  
Without further checking, this behavior might origin in the deactivated call of `SoilWater()` in [Hydrology2Mod.F90 L231-L234](https://github.com/HPSCTerrSys/TSMP/blob/master/bldsva/intf_oas3/clm3_5/tsmp/Hydrology2Mod.F90#L231-L234) in case of  involved ParFlow model.

**Comment by DCaviedesV** [comment]
Is any action required concerning this issue? Or can this be closed?

**Comment by niklaswr** [comment]
Can be closed as this is more DETECT related and is already an issue in the [DETECT discussion](https://gitlab.jsc.fz-juelich.de/detect/detect_z03_z04/discussions/-/issues/1).
