### ISSUE TITLE
TSMP fix mask applied to coupling fields

### ISSUE THREAD

**Issue by niklaswr** [HPSCTerrSys/TSMP#155]
## Fix mask applied to coupling fields
Depending on individual component model the coupled fields have to be masked.  
One example is ParFlow which in current setting mask out open water bodies from model domain and related pixels does hold masking values as e.g. `1e+38`. Those values are absolutely nonphysically and should not passed to other coupled component models.  

To my understanding this masking is handled for each component model separately in both sending and receiving function by setting pixels to mask to a neutral value of e.g. `0`.  
However, CLM3.5 is not sending zero values for masked pixels but `-999999` (example see [send_fls_2pfl.F90 L166-L167](https://github.com/HPSCTerrSys/TSMP/blob/master/bldsva/intf_oas3/clm3_5/oas3/send_fld_2pfl.F90#L166-L167)).   
This is not a problem as long as ParFlow cuts out from model domain (mask with `.pfsol` file) the exact same pixels as CLM3.5 does, but this is a problem if this is not the case, as ParFlow than receives a permanently forcing of `-999999` leading to crash very quick.  

There are use-cases where cutting the ParFlow domain with a `.pfsol` files is not applicable as e.g. running on GPU or running with 'active' inland lakes, wherefore I suggest to fix / workaround / solve this issue within the official TSMP version.

For my local experiment I solved the problem with the following TSMP patch:
[patch_ForceClmToSendZero.txt](https://github.com/HPSCTerrSys/TSMP/files/10491554/patch_ForceClmToSendZero.txt)
However, Im not sure if this is a full solution, or if this does cover special machines etc. only, as Im not well versed with the patching logic. 

Therefore, the request for consideration and incorporation.

**Comment by s-poll** [comment]
I would like to close this issue as sending non-physical values from CLM for non-updated grid points for whatever reason seems fine. The handling of inactive grid points in CLM and active grid points in ParFlow should be treated in the ParFlow receive module. A more in depth discussion can be found in PR #160. 

Please reopen the issue if you object.
