### ISSUE TITLE
Prepare TSMP for Stages/2023 on JUWELS/JURECA

### ISSUE THREAD

**Issue by ivzhukov** [HPSCTerrSys/TSMP#156]
As Stages/2023 will be default soon on JUWELS/JURECA it is necessary to build/test TSMP with the latest software stack.

**Comment by ivzhukov** [comment]
The following modules were used 
```
module --force purge
module use $OTHERSTAGES
module load Stages/2023
module load Intel/2022.1.0
module load ParaStationMPI/5.7.0-1
#
module load Hypre/2.27.0
module load Silo/4.11
module load Tcl/8.6.12 # this version is not compatible with ParFlow3.2
#
module load ecCodes/2.27.0 
module load HDF5/1.12.2-serial #HDF5/1.12.1
module load netCDF/4.9.0
module load netCDF-Fortran/4.6.0
module load PnetCDF/1.12.3
module load cURL/7.83.0
module load Szip/.2.1.1 
module load Python/3.10.4
module load NCO/5.0.3  # not available for Stage 2023
module load CMake/3.23.1
module load git/2.36.0-nodocs  # !!! gleich zu git/2.28.0
```

**Comment by ivzhukov** [comment]
@Jörg: could you please look into the proposed solutions?

**Comment by ivzhukov** [comment]
EB team will install HYPRE w/o CUDA for Stages/2023 (Intel/2022.1.0+ParaStationMPI/5.7.0-1) by next week

**Comment by ivzhukov** [comment]
Hypre/2.27.0-cpu is now available on Stages/2023. @joergbenke can you test TSMP installation with it?

**Comment by joergbenke** [comment]
@ivzhukov Thank you very much! I will test it today!

**Comment by ivzhukov** [comment]
Hypre/2.27.0-cpu is now available with Stages/2023 on DEEP. @joergbenke could you please test it?

**Comment by joergbenke** [comment]
I will do the testing but maybe at the beginning of april, because I have to do other stuff

**Comment by DCaviedesV** [comment]
is there a branch / fork for this `Stages/2023` preparation?
is it tested on JURECA /JUWELS. I understand not yet in DEEP... but with JURECA/JUWELS we might include this in the release candidate.

**Comment by chartick** [comment]
I have also tested it and included Stage/2023 at least as an additional option in clean_setup. The status at the moment is that the **master** is still on 2020 and **msa_build_interface** is on 2022. Maybe we could directly move to 2023 because 2022 and 2023 both require ParFlow 3.12 and do not work with 3.9 which is still mentioned in the quick start.
