### ISSUE TITLE
DOC: Migrate existing tsmp_manual repo from JSC GitLab to GitHub

### ISSUE THREAD

**Issue by niklaswr** [HPSCTerrSys/TSMP#164]
## Migrate existing tsmp_manual repo from JSC GitLab to GitHub

As a first step, after the technical implementation of GitHub Page based documentation, the existing documentation located in [TSMP_manual](https://gitlab.jsc.fz-juelich.de/sdlts/tsmp_manual) has to be migrated to GitHub, just as it is, without any reformatting. 
As we agreed to process with a PR based workflow, I will provide / link the related PR asap.

One question that arises in this context is **how do we agree on a PR**?
We can create a PR and link it to an open issue to properly discuss the changes made. However, I think we need some technical criteria to decide if the PR can be merged or not. Otherwise, each PR is an individual issue, and you have to ask everyone for acceptance. 

I suggest that we just go through reviews. 
When you open a PR, you also assign a reviewer. If that reviewer accepts the changes, then the PR can be merged. If the assigned reviewer is unsure, this can be discussed within the issue, or another reviewer can be assigned. 
Please do comment on this, as I want to merge the final agreed concept into the documentation with the same PR associated with the issue.

**Comment by jjokella** [comment]
my input general PR handling: I would say we define some admins (i.e. us) that can merge PRs. Everyone else would need approval from one of us. For `master` maybe it can be stricter, for `TSMP_pdaf` f.e. I would like to keep full rights for quick changes.

Regarding Doc-Migration. On my fork I get an error that the URL is not reachable (see below). @niklaswr This is not a general problem though, right?

https://github.com/jjokella/TSMP/actions/runs/4301755845/workflow

**Comment by niklaswr** [comment]
This should not be a general problem, but an interesting one...
Most likely the important error message is 

`remote: Permission denied on jjokella/TSMP.git for github-actions[bot].`

Do you have any gitHub rules that protect your `gh-pages` branch?
Do you have a personal [GitHub access token](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) that allows you to use the GitHub API?

**Comment by jjokella** [comment]
> Do you have any gitHub rules that protect your `gh-pages` branch?
Not that I am aware of.

> Do you have a personal [GitHub access token](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) that allows you to use the GitHub API?
I do not!
