### ISSUE TITLE
TSMP error on JUWELS

### ISSUE THREAD

**Issue by hydrogencl** [HPSCTerrSys/TSMP#234]
## Describe the problem
A clear and concise description of what the error is

## Version and Component Models 
TSMP-Version: d1fa2a

Build command:
``` bash
	./build_tsmp.ksh -c clm3-cos5-pfl -m JUWELS -O Intel
```

## Machine
JUWELS
## Error message
``` bash
  clear oas dir: /p/project/exaww/esm-buildbot/ESM_JUWELS/TerrSysMP/build/oasis3-mct_JUWELS_clm3-cos5-pfl    ... OK!
  backup oas dir to: /p/project/exaww/esm-buildbot/ESM_JUWELS/TerrSysMP/build/oasis3-mct_JUWELS_clm3-cos5-pfl    ... error!!! - aborting...
See /p/project/exaww/esm-buildbot/ESM_JUWELS/TerrSysMP/build/bldsva/log_all_200924-092645.txt and /p/project/exaww/esm-buildbot/ESM_JUWELS/TerrSysMP/build/bldsva/err_all_200924-092645.txt

```

```bash
    cp: cannot stat '/p/project/exaww/esm-buildbot/ESM_JUWELS/TerrSysMP/build/oasis3-mct': No such file or directory
```

## Expected behavior
Should be working out-of-box on JUWELS?

I think the oasis3-mct is not cloned and installed?

**Comment by DCaviedesV** [comment]
The `build_tsmp.ksh` script does not automatically clone components, which you may have expected. You need to clone them manually or in a higher level script.

**Comment by hydrogencl** [comment]
ok thanks! I will try this later

**Comment by jjokella** [comment]
This page of the manual should solve the issue: https://hpscterrsys.github.io/TSMP/content/build_tsmp/obtain_code.html
