### ISSUE TITLE
ToDo for TSMP on github: push the previous tags, before v1.2.1 to the github also (Bugzilla Bug 51)

### ISSUE THREAD

**Issue by DCaviedesV** [HPSCTerrSys/TSMP#51]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 51
Date: 2020-02-04 13:54:54 +0100
From: Klaus Goergen &lt;<k.goergen@fz-juelich.de>&gt;
To:   Abouzar Ghasemi, &lt;<a.ghasemi@fz-juelich.de>&gt;
CC:   a.ghasemi@fz-juelich.de, n.wagner@fz-juelich.de

Last updated: 2020-02-04 13:54:54 +0100

## Comment 87
Date: 2020-02-04 13:54:54 +0100
From: Klaus Goergen &lt;<k.goergen@fz-juelich.de>&gt;

effectively associate a revision with a tag

**Comment by DCaviedesV** [comment]
@kgoergen do we have an overview o previous tags to do this for completeness? Or shall we close this and consider it currently irrelevant?

**Comment by kgoergen** [comment]
I would consider it right now irrelevant. It was intended to be included for reproducibility and provenance. Close for now.
