### ISSUE TITLE
ToDo for TSMP on GitHub: remove spaces before commands in code-blocks (Bugzilla Bug 63)

### ISSUE THREAD

**Issue by DCaviedesV** [HPSCTerrSys/TSMP#63]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 63
Date: 2020-02-12 18:18:29 +0100
From: Niklas Wagner &lt;<n.wagner@fz-juelich.de>&gt;
To:   Abouzar Ghasemi, &lt;<a.ghasemi@fz-juelich.de>&gt;
CC:   a.ghasemi@fz-juelich.de, n.wagner@fz-juelich.de

Last updated: 2020-02-12 18:18:29 +0100

## Comment 105
Date: 2020-02-12 18:18:29 +0100
From: Niklas Wagner &lt;<n.wagner@fz-juelich.de>&gt;

There are leading spaces before each command in every code-block. Remove those, because copy and past these commands can lead to odd behavior in terminal.

**Comment by niklaswr** [comment]
This is outdated with the new documentation.
So as Im the owner of the original bug report in BugZilla I will close this issue.
